version: "2.0"
services:
  web:
    image: kahilav1/twitter-dashboard-on-akash
    env:
      - TWITTER_KEY=<insert key>
      - TWITTER_IDS=<insert ids, e.g. "elonmusk realtrump">
      - DATABASE_URL=<insert url (optional, remove this line if not used)>
      - PAGE_TITLE=<insert page title>
      - INTRODUCTION_TEXT=<insert introduction text>
      - ADMIN_TWITTER_ID=<insert your twitter id (optional, remove this line if not used)>
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1